import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e3e2e0",
        "surface-container-low": "#f4f3f1",
        "surface": "#faf9f6",
        "on-primary-fixed": "#0d1b36",
        "on-secondary-fixed": "#001d31",
        "surface-dim": "#dbdad7",
        "on-error-container": "#93000a",
        "on-surface-variant": "#45464d",
        "on-secondary-fixed-variant": "#2b4963",
        "on-error": "#ffffff",
        "surface-container": "#efeeeb",
        "on-primary-container": "#7c89aa",
        "secondary-fixed": "#cce5ff",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-surface": "#1a1c1a",
        "inverse-on-surface": "#f2f1ee",
        "on-background": "#1a1c1a",
        "on-tertiary-container": "#ad8233",
        "secondary-fixed-dim": "#abcae8",
        "on-secondary-container": "#46647e",
        "tertiary": "#130a00",
        "on-primary-fixed-variant": "#3a4664",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2f312f",
        "inverse-primary": "#b9c6ea",
        "primary": "#0B132B",
        "tertiary-container": "#301f00",
        "tertiary-fixed-dim": "#f0bf6a",
        "tertiary-fixed": "#ffdeab",
        "outline-variant": "#c5c6ce",
        "on-tertiary-fixed-variant": "#5f4100",
        "primary-container": "#14213d",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e3e2e0",
        "surface-container-high": "#e9e8e5",
        "primary-fixed-dim": "#b9c6ea",
        "surface-bright": "#faf9f6",
        "secondary-container": "#c1e0ff",
        "on-tertiary": "#ffffff",
        "surface-tint": "#525e7d",
        "on-primary": "#ffffff",
        "secondary": "#43617c",
        "primary-fixed": "#d9e2ff",
        "outline": "#75777e",
        "background": "#faf9f6",
        "brass": {
          DEFAULT: "#B88628",
          hover: "#9E7220",
          light: "#ffdeab",
          dim: "#f0bf6a",
        },
        "slate": {
          DEFAULT: "#3E5C76",
          dark: "#14213d",
          light: "#abcae8",
        },
        "hairline": "#E5E2DA",
      },
      borderRadius: {
        DEFAULT: "6px",
        xs: "3px",
        sm: "4px",
        md: "6px",
        lg: "10px",
        xl: "14px",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "gutter": "24px",
        "unit": "4px",
        "container-max-width": "1280px",
      },
      fontFamily: {
        headline: ["var(--font-fraunces)", "serif"],
        body: ["var(--font-inter)", "sans-serif"],
        "headline-xl": ["var(--font-fraunces)", "serif"],
        "headline-lg": ["var(--font-fraunces)", "serif"],
        "headline-md": ["var(--font-fraunces)", "serif"],
        "headline-lg-mobile": ["var(--font-fraunces)", "serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
        "label-sm": ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
      },
      boxShadow: {
        hairline: "0 0 0 1px #E5E2DA",
        editorial: "0 12px 32px rgba(20, 33, 61, 0.08)",
      },
    },
  },
  plugins: [],
};

export default config;
